export const QUESTIONS = [
  {
    id: "q1",
    number: 1,
    level: "LEVEL 1｜先看研究說了什麼",
    type: "accuracy",
    label: "準確題",
    prompt: "研究指出，青少年睡眠不足可能造成什麼影響？",
    options: [
      { key: "A", text: "只會讓人假日比較晚起床" },
      { key: "B", text: "可能影響注意力與學習表現" },
      { key: "C", text: "一定不會影響白天的狀態" },
      { key: "D", text: "只會影響身高，不會影響其他表現" },
    ],
    answer: "B",
    explanation: "先不要只看一句結論，接下來要追查：這個說法是誰研究的、研究對象是誰，以及原始研究到底支持到哪裡。",
  },
  {
    id: "q2",
    number: 2,
    level: "LEVEL 1｜來源在哪裡",
    type: "accuracy",
    label: "準確題",
    prompt: "如果你要追查一則健康新聞的研究依據，下列哪一頁最值得繼續打開？",
    options: [
      { key: "A", text: "新聞網站的搜尋結果摘要" },
      { key: "B", text: "健康網站重新整理的短文" },
      { key: "C", text: "可以辨認研究標題、作者或期刊的研究頁面" },
      { key: "D", text: "沒有來源連結的 AI 回答" },
    ],
    answer: "C",
    explanation: "找到研究頁面，才有機會核對標題、作者、年份、出版來源與研究內容。",
  },
  {
    id: "q3",
    number: 3,
    level: "LEVEL 1｜不要被標題帶走",
    type: "accuracy",
    label: "準確題",
    prompt: "看到一篇說『睡眠不足會影響學習』的新聞時，下一步最適合做什麼？",
    options: [
      { key: "A", text: "直接把新聞標題當成證據" },
      { key: "B", text: "找到新聞引用的研究，再核對研究內容" },
      { key: "C", text: "只看留言區大家是否同意" },
      { key: "D", text: "請 AI 判斷新聞一定正確" },
    ],
    answer: "B",
    explanation: "新聞是線索，不是追查的終點。",
  },
  {
    id: "q4",
    number: 4,
    level: "LEVEL 2｜辨認真正來源",
    type: "speed",
    label: "⚡ 搶快題",
    prompt: "共用模擬新聞：『2025年，某大學研究團隊發現青少年睡眠與學習表現有關，研究刊登於 Sleep Health。』下列哪個線索最有辨識力？",
    options: [
      { key: "A", text: "新聞使用了很吸引人的標題" },
      { key: "B", text: "研究標題、作者／研究團隊、年份與期刊 Sleep Health 可以互相核對" },
      { key: "C", text: "新聞圖片看起來像實驗室" },
      { key: "D", text: "搜尋結果摘要剛好出現相同的一句話" },
    ],
    answer: "B",
    explanation: "能交叉核對、能回到原始出版來源的線索，才有辨識力。",
  },
  {
    id: "q5",
    number: 5,
    level: "LEVEL 2｜檢查研究範圍",
    type: "multi",
    label: "多選題",
    prompt: "閱讀研究資料時，哪些資訊值得一起記下來？（至少選 3 個）",
    options: [
      { key: "A", text: "研究對象" },
      { key: "B", text: "研究時間或年份" },
      { key: "C", text: "測量或蒐集資料的方法" },
      { key: "D", text: "研究限制" },
      { key: "E", text: "文章的字體大小" },
    ],
    answer: ["A", "B", "C", "D"],
    explanation: "研究對象、時間、方法與限制，都會影響結論能說到哪裡。",
  },
  {
    id: "q6",
    number: 6,
    numberLabel: "開放題",
    level: "LEVEL 2｜把問題變成搜尋詞",
    type: "open",
    label: "💬 開放題",
    prompt: "如果要找到『青少年睡眠與學習表現』的研究，你會輸入哪些搜尋詞？",
    answer: null,
    explanation: "好的搜尋詞能同時保留研究對象、主題與可能的出版線索。",
  },
  {
    id: "q7",
    number: 7,
    level: "LEVEL 2｜逐步縮小搜尋",
    type: "accuracy",
    label: "準確題",
    prompt: "下列哪一組搜尋詞最適合開始追查？",
    options: [
      { key: "A", text: "睡覺 很重要" },
      { key: "B", text: "2025 Sleep Health 青少年 睡眠" },
      { key: "C", text: "大家都說睡眠不足" },
      { key: "D", text: "AI 幫我找答案" },
    ],
    answer: "B",
    explanation: "年份、期刊、研究對象與主題能協助你從寬泛搜尋逐步縮小範圍。",
  },
  {
    id: "q8",
    number: 8,
    level: "LEVEL 3｜看懂搜尋結果",
    type: "accuracy",
    label: "準確題",
    prompt: "搜尋結果同時出現新聞、健康網站、研究頁面與 AI 摘要。哪一個最適合用來核對研究細節？",
    options: [
      { key: "A", text: "新聞標題" },
      { key: "B", text: "健康網站的整理段落" },
      { key: "C", text: "真正打開的研究頁面" },
      { key: "D", text: "AI 摘要中的一句話" },
    ],
    answer: "C",
    explanation: "摘要可以當線索，但不能取代你真正打開、閱讀與核對的來源。",
  },
  {
    id: "q9",
    number: 9,
    level: "LEVEL 3｜結論能說到哪裡",
    type: "accuracy",
    label: "準確題",
    prompt: "你找到一篇英文研究，研究對象是大學生；但新聞說的是『青少年』。最合理的判斷是什麼？",
    options: [
      { key: "A", text: "研究對象不同沒關係，可以直接套用" },
      { key: "B", text: "只要研究年份一樣，結論就一定適用" },
      { key: "C", text: "要標記研究對象不完全相符，不能直接把結論說成適用所有青少年" },
      { key: "D", text: "英文研究一定比新聞可靠，所以直接改寫新聞" },
    ],
    answer: "C",
    explanation: "研究對象不同，結論的適用範圍就需要重新判斷。",
  },
];

export const ACTIVE_QUESTION_INDEX = 0;
export const ACTIVE_QUESTION = QUESTIONS[ACTIVE_QUESTION_INDEX];
export const SESSION_ID = "tomorrow-class";
